server.port=8989


jwt.secret=lRU5CfHk3yhrDTBmU8R11fDW69i64CitEkvsifzyV7iq2VzXFM9ejc1cgqWy5vASdhbxzfY8Sj79cb8nPPWuA9hHyLcej2UU4ozvBAZQ8fdq4bSsiMXI0K8R
jwt.get.token.uri=/inokscam/rest/api/auth/authenticate


spring.servlet.multipart.max-file-size=100000KB
spring.servlet.multipart.max-request-size=100000KB


#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=samar.neji@esprit.tn
#spring.mail.password=boqrnkqkoyawizbv
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


spring.datasource.url=jdbc:mysql://5.135.194.240:3306/homeJek?enabledTLSProtocols=TLSv1.2&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
spring.datasource.username=homeJek
spring.datasource.password=//homeJek2022++
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql=false
